services:
  api:
    extends:
     file: ./back/docker-compose.yml
     service: api
  db:
    extends:
     file: ./back/docker-compose.yml
     service: db

  adminer:
    extends:
     file: ./back/docker-compose.yml
     service: adminer
