node {
    stage("Clone the project") {
        git branch: 'master', url: 'https://github.com/Nietsab/MyRestoV2.git'
        sh "cd myrestoV2/back"
    }

    stage("connect docker") {
        sh "docker -v"
    }

    stage("Compilation") {
        sh "./mvnw clean install -DskipTests"
    }

    stage("Tests") {
        stage("Running unit tests") {
            sh "./mvnw test -Punit"
        }
    }
}